### ISSUE TITLE
Checklist of things before the CLI v0.0.13 release

### ISSUE THREAD

**Issue by muneeb-ali** [stx-labs/stacks.js#105]
I'm creating this issue to capture, at a high level, the important remaining tasks/issues for the CLI v0.0.13 release.

**Comment by muneeb-ali** [comment]
I'll update this issue as I gather the current status and report back on test results.

**Comment by muneeb-ali** [comment]
Using the same (high-level) issue to track the respective server release as well.

**Comment by muneeb-ali** [comment]
Some things that are going on right now: 
- [x] Test 0.0.13 server bootup from genesis block (multiple instances) to compare consensus hash
- [x] Test Blockstack server 0.0.13 PyPi installation on fresh Debian instances 
- [x] Test Blockstack CLI 0.0.13 PyPi installation on fresh Debian instances 
- [x] More/final testing of Blockstack CLI register operations on Bitcoin mainnet (not testnet)

**Comment by jcnelson** [comment]
Pushed!
