### ISSUE TITLE
Breaking changes for stacks.js

### ISSUE THREAD

**Issue by janniks** [stx-labs/stacks.js#1642]
more steps to come 😉

- [x] #1655
- [x] #1703 
- [x] allow use of Network or Name everywhere possible
- [x] allow Clarity values to also use number/string/bigint
- [x] refactor to use asset-info string everywhere possible, refactor to contract-address-id strings (.) (::)
  - [x] rename `NftString` to Asset, since it's the same for FT contracts, update the builders as well
- [x] prefer string addresses everywhere (maybe doesn't need to be message type)
- [x] make all methods use new network obj, instead of chain-id etc.
- [x] consolidate capitalization (camel case vs STX/ID)
- [x] remove structured signature from message types (and other non-needed wrapper types)

non-breaking (extra credit)
- [ ] add pox tuple address helper to the Cl. namespace
- [ ] add missing tx creation checks (e.g. contract name too long)
- [ ] add detectable (control flowable) errors everywhere
	e.g. FetchError for anything that failed during fetch
	errors should still just be a string (and maybe a .originalError)
- [ ] clean imports everywhere
- [x] get rid of comments using [[]] syntax
- [ ] clean up manual re-exports and always export where defined
